# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gg.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 550)
        MainWindow.setMinimumSize(QtCore.QSize(940, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 0, 160, 550))
        self.menu.setMinimumSize(QtCore.QSize(160, 450))
        self.menu.setStyleSheet("QFrame {\n"
"    background-color: rgb(45, 52, 62);\n"
"    color: rgb(231, 255, 252);\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.sfe = QtWidgets.QLabel(self.menu)
        self.sfe.setGeometry(QtCore.QRect(0, 166, 160, 19))
        self.sfe.setMinimumSize(QtCore.QSize(160, 0))
        self.sfe.setMaximumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sfe.setFont(font)
        self.sfe.setStyleSheet("")
        self.sfe.setLineWidth(1)
        self.sfe.setObjectName("sfe")
        self.extr_sf = QtWidgets.QPushButton(self.menu)
        self.extr_sf.setGeometry(QtCore.QRect(5, 246, 150, 30))
        self.extr_sf.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.extr_sf.setFont(font)
        self.extr_sf.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(73, 84, 100);\n"
"}")
        self.extr_sf.setObjectName("extr_sf")
        self.lsb = QtWidgets.QLabel(self.menu)
        self.lsb.setGeometry(QtCore.QRect(0, 296, 160, 19))
        self.lsb.setMinimumSize(QtCore.QSize(160, 0))
        self.lsb.setMaximumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lsb.setFont(font)
        self.lsb.setObjectName("lsb")
        self.ins_lsb = QtWidgets.QPushButton(self.menu)
        self.ins_lsb.setGeometry(QtCore.QRect(5, 336, 150, 30))
        self.ins_lsb.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ins_lsb.setFont(font)
        self.ins_lsb.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.ins_lsb.setObjectName("ins_lsb")
        self.extr_lsb = QtWidgets.QPushButton(self.menu)
        self.extr_lsb.setGeometry(QtCore.QRect(5, 376, 150, 30))
        self.extr_lsb.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.extr_lsb.setFont(font)
        self.extr_lsb.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(73, 84, 100);\n"
"}")
        self.extr_lsb.setObjectName("extr_lsb")
        self.ins_sf = QtWidgets.QPushButton(self.menu)
        self.ins_sf.setGeometry(QtCore.QRect(5, 206, 150, 30))
        self.ins_sf.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ins_sf.setFont(font)
        self.ins_sf.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.ins_sf.setObjectName("ins_sf")
        self.abt = QtWidgets.QPushButton(self.menu)
        self.abt.setGeometry(QtCore.QRect(5, 480, 150, 30))
        self.abt.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.abt.setFont(font)
        self.abt.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(73, 84, 100);\n"
"}")
        self.abt.setObjectName("abt")
        self.label = QtWidgets.QLabel(self.menu)
        self.label.setGeometry(QtCore.QRect(10, 485, 21, 21))
        self.label.setStyleSheet("QLabel {\n"
"    background-color: transparent\n"
"\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/info-btn.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.insrt_ico = QtWidgets.QLabel(self.menu)
        self.insrt_ico.setGeometry(QtCore.QRect(10, 210, 21, 21))
        self.insrt_ico.setStyleSheet("QLabel {\n"
"    background-color: transparent\n"
"\n"
"}")
        self.insrt_ico.setText("")
        self.insrt_ico.setPixmap(QtGui.QPixmap("icons/insert.png"))
        self.insrt_ico.setScaledContents(True)
        self.insrt_ico.setObjectName("insrt_ico")
        self.extr_ico = QtWidgets.QLabel(self.menu)
        self.extr_ico.setGeometry(QtCore.QRect(12, 251, 21, 21))
        self.extr_ico.setStyleSheet("QLabel {\n"
"    background-color: transparent\n"
"\n"
"}")
        self.extr_ico.setText("")
        self.extr_ico.setPixmap(QtGui.QPixmap("icons/extr.png"))
        self.extr_ico.setScaledContents(True)
        self.extr_ico.setObjectName("extr_ico")
        self.insrt_ico_2 = QtWidgets.QLabel(self.menu)
        self.insrt_ico_2.setGeometry(QtCore.QRect(10, 340, 21, 21))
        self.insrt_ico_2.setStyleSheet("QLabel {\n"
"    background-color: transparent\n"
"\n"
"}")
        self.insrt_ico_2.setText("")
        self.insrt_ico_2.setPixmap(QtGui.QPixmap("icons/insert.png"))
        self.insrt_ico_2.setScaledContents(True)
        self.insrt_ico_2.setObjectName("insrt_ico_2")
        self.extr_ico_2 = QtWidgets.QLabel(self.menu)
        self.extr_ico_2.setGeometry(QtCore.QRect(11, 381, 21, 21))
        self.extr_ico_2.setStyleSheet("QLabel {\n"
"    background-color: transparent\n"
"\n"
"}")
        self.extr_ico_2.setText("")
        self.extr_ico_2.setPixmap(QtGui.QPixmap("icons/extr.png"))
        self.extr_ico_2.setScaledContents(True)
        self.extr_ico_2.setObjectName("extr_ico_2")
        self.label_6 = QtWidgets.QLabel(self.menu)
        self.label_6.setGeometry(QtCore.QRect(21, 0, 118, 118))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("imgs/logof.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.menu)
        self.line.setGeometry(QtCore.QRect(21, 135, 118, 5))
        self.line.setStyleSheet("Line {\n"
"    border-top: 3px dotted rgb(162, 219, 250);\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(160, 0, 780, 550))
        self.frame_2.setStyleSheet("QFrame {\n"
"    background-color: rgb(244, 244, 242);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.img_dst = QtWidgets.QLabel(self.frame_2)
        self.img_dst.setGeometry(QtCore.QRect(400, 80, 320, 240))
        self.img_dst.setText("")
        self.img_dst.setPixmap(QtGui.QPixmap("imgs/def.svg"))
        self.img_dst.setScaledContents(True)
        self.img_dst.setObjectName("img_dst")
        self.img_src = QtWidgets.QLabel(self.frame_2)
        self.img_src.setGeometry(QtCore.QRect(40, 80, 320, 240))
        self.img_src.setStyleSheet("QLabel {\n"
" border-color: rgb(73, 84, 100);\n"
"}")
        self.img_src.setText("")
        self.img_src.setPixmap(QtGui.QPixmap("imgs/def.svg"))
        self.img_src.setScaledContents(True)
        self.img_src.setWordWrap(False)
        self.img_src.setObjectName("img_src")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(120, 25, 141, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
" color: rgb(73, 84, 100);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(480, 25, 161, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
" color: rgb(73, 84, 100);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.keyf = QtWidgets.QLineEdit(self.frame_2)
        self.keyf.setGeometry(QtCore.QRect(233, 340, 130, 28))
        self.keyf.setStyleSheet("QLineEdit {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    border: 2px solid rgb(28, 42, 63);\n"
"}")
        self.keyf.setText("")
        self.keyf.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.keyf.setReadOnly(False)
        self.keyf.setObjectName("keyf")
        self.start = QtWidgets.QPushButton(self.frame_2)
        self.start.setGeometry(QtCore.QRect(130, 338, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.start.setObjectName("start")
        self.browse = QtWidgets.QPushButton(self.frame_2)
        self.browse.setGeometry(QtCore.QRect(25, 338, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.browse.setFont(font)
        self.browse.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.browse.setObjectName("browse")
        self.res_bttn = QtWidgets.QPushButton(self.frame_2)
        self.res_bttn.setGeometry(QtCore.QRect(400, 338, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.res_bttn.setFont(font)
        self.res_bttn.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"")
        self.res_bttn.setObjectName("res_bttn")
        self.mdf_bttn = QtWidgets.QPushButton(self.frame_2)
        self.mdf_bttn.setGeometry(QtCore.QRect(590, 338, 130, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.mdf_bttn.setFont(font)
        self.mdf_bttn.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"")
        self.mdf_bttn.setObjectName("mdf_bttn")
        self.phase = QtWidgets.QLabel(self.frame_2)
        self.phase.setGeometry(QtCore.QRect(275, 0, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.phase.setFont(font)
        self.phase.setStyleSheet("QLabel {\n"
"    color: rgb(255, 101, 132);\n"
"\n"
"}")
        self.phase.setObjectName("phase")
        self.img_lg = QtWidgets.QLabel(self.frame_2)
        self.img_lg.setGeometry(QtCore.QRect(230, 380, 140, 130))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.img_lg.setFont(font)
        self.img_lg.setStyleSheet("QLabel {\n"
"    color: rgb(73, 84, 100);\n"
"    border-radius: 8px;\n"
"    border: 1px solid  gray;\n"
"}")
        self.img_lg.setText("")
        self.img_lg.setPixmap(QtGui.QPixmap("imgs/log_img.svg"))
        self.img_lg.setScaledContents(True)
        self.img_lg.setObjectName("img_lg")
        self.lg_label = QtWidgets.QLabel(self.frame_2)
        self.lg_label.setGeometry(QtCore.QRect(280, 520, 110, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.lg_label.setFont(font)
        self.lg_label.setStyleSheet("QLabel {\n"
" color: rgb(73, 84, 100);\n"
"}")
        self.lg_label.setObjectName("lg_label")
        self.browse_lg = QtWidgets.QPushButton(self.frame_2)
        self.browse_lg.setGeometry(QtCore.QRect(130, 480, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.browse_lg.setFont(font)
        self.browse_lg.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.browse_lg.setObjectName("browse_lg")
        self.psnr_f = QtWidgets.QLineEdit(self.frame_2)
        self.psnr_f.setGeometry(QtCore.QRect(590, 482, 130, 28))
        self.psnr_f.setStyleSheet("QLineEdit {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 8px;\n"
"    border: 2px solid rgb(28, 42, 63);\n"
"}")
        self.psnr_f.setText("")
        self.psnr_f.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.psnr_f.setReadOnly(True)
        self.psnr_f.setObjectName("psnr_f")
        self.psnr_bttn = QtWidgets.QPushButton(self.frame_2)
        self.psnr_bttn.setGeometry(QtCore.QRect(400, 480, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.psnr_bttn.setFont(font)
        self.psnr_bttn.setStyleSheet("QPushButton {\n"
"    color: rgb(73, 84, 100);\n"
"    background-color: rgb(187, 191, 202);\n"
"    border-radius: 8px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 69, 96)\n"
"}")
        self.psnr_bttn.setObjectName("psnr_bttn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sfe.setText(_translate("MainWindow", "     Self-Embedding"))
        self.extr_sf.setText(_translate("MainWindow", "Exract"))
        self.lsb.setText(_translate("MainWindow", "    Image Embedding"))
        self.ins_lsb.setText(_translate("MainWindow", "Insert"))
        self.extr_lsb.setText(_translate("MainWindow", "Extract"))
        self.ins_sf.setText(_translate("MainWindow", "Embed"))
        self.abt.setText(_translate("MainWindow", "About"))
        self.label_2.setText(_translate("MainWindow", "Image Source"))
        self.label_5.setText(_translate("MainWindow", "Image Résultat"))
        self.keyf.setPlaceholderText(_translate("MainWindow", "  Key"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.res_bttn.setText(_translate("MainWindow", "Reconstruct"))
        self.mdf_bttn.setText(_translate("MainWindow", "Detect modifications"))
        self.phase.setText(_translate("MainWindow", "Self-Embedding - Embed Phase"))
        self.lg_label.setText(_translate("MainWindow", "Logo"))
        self.browse_lg.setText(_translate("MainWindow", "Browse"))
        self.psnr_f.setPlaceholderText(_translate("MainWindow", "Value"))
        self.psnr_bttn.setText(_translate("MainWindow", "PSNR"))
